apiVersion: v1
kind: Service

metadata:
  name: envops-frontend
  namespace: envops-core
  labels:
    app.kubernetes.io/name: envops-frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: envops

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: envops-frontend

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP