apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0ae7aa0b48e65c42d #need to change from fixed value to dynamic one (enhancement)
  directoryPerms: "700"
reclaimPolicy: Retain
volumeBindingMode: Immediate