apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-secrets-sa
  namespace: envops-core
  # add accounrt ID to the role ARN below
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::524558748637:role/envops-eso-secrets-role

