apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-credentials
  namespace: envops-core
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: backend-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SBG_API_KEY: "{{ .sbg_api_key }}"
  data:
    - secretKey: sbg_api_key
      remoteRef:
        key: envops/backend-credentials
        property: sbg_api_key