# Kubernetes/secrets-management/externalsecret-redis.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: envops-core
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: localstack-secrets-store
    kind: SecretStore
  target:
    name: redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: envops/redis-credentials
        property: password