apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: localstack-secrets-store
  namespace: envops-core
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: localstack-creds
            key: access-key
          secretAccessKeySecretRef:
            name: localstack-creds
            key: secret-access-key
