persistence:
  enabled: true
  storageClass: efs-sc
  size: 20Gi

controller:

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    path: /
    pathType: Prefix
    jenkinsUrlProtocol: "http"

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

  serviceAccount:
    create: true
    name: jenkins-controller-sa

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - github-oauth
    - github-branch-source
    - matrix-auth

  overwritePlugins: true
  healthProbes: true

  csrf:
    defaultCrumbIssuer:
      enabled: true
      proxyCompatibility: true

  JCasC:
    enabled: true
    configScripts:
      security: |
        jenkins:
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false

      kubernetes-cloud: |
        jenkins:
          clouds:
            - kubernetes:
                name: "eks-cluster"
                namespace: "cicd"
                serverUrl: "https://kubernetes.default.svc"
                jenkinsUrl: "http://NGINX-LOAD-BALANCER-DNS"

                webSocket: true

                templates:
                  - name: "default-agent"
                    label: "jenkins-agent"

                    serviceAccount: "jenkins-agent-sa"

                    workspaceVolume:
                      emptyDirWorkspaceVolume: {}

                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        args: "${computer.jnlpmac} ${computer.name}"

                      - name: "kaniko"
                        image: "gcr.io/kaniko-project/executor:v1.23.2-debug"
                        command: "sleep"
                        args: "infinity"

agent:
  serviceAccount:
    name: jenkins-agent-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::524558748637:role/jenkins-agent-role