controller:
  JCasC:
    enabled: true

    configScripts:

      kubernetes-cloud: |
        jenkins:
          clouds:
            - kubernetes:
                name: "eks-cluster"
                namespace: "cicd"
                serverUrl: "https://kubernetes.default.svc"
                jenkinsUrl: "http://a936da9d40fbb48aa907d72b19ac6e83-418695135.us-east-1.elb.amazonaws.com"

                webSocket: true

                templates:
                  - name: "default-agent"
                    label: "jenkins-agent"
                    serviceAccount: "jenkins-agent-sa"


                    workspaceVolume:
                      emptyDirWorkspaceVolume: {}

                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        args: "${computer.jnlpmac} ${computer.name}"

                      - name: "node"
                        image: "node:22"
                        command: "sleep"
                        args: "infinity"

                      - name: "kaniko"
                        image: "gcr.io/kaniko-project/executor:v1.23.2-debug"
                        command: "sleep"
                        args: "infinity"

      security: |
        jenkins:
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false

  containerEnv:
    - name: GIT_CONFIG_COUNT
      value: "1"

    - name: GIT_CONFIG_KEY_0
      value: "safe.directory"

    - name: GIT_CONFIG_VALUE_0
      value: "*"

  csrf:
    defaultCrumbIssuer:
      enabled: true
      proxyCompatibility: true

  healthProbes: true

  ingress:
    enabled: true
    ingressClassName: nginx

    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

    jenkinsUrlProtocol: http
    path: /
    pathType: Prefix

  installPlugins:
    - kubernetes:4547.v52f3080db_8cd
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.10.1
    - configuration-as-code:2117.vc05a_0b_e6b_f4e
    - github-oauth:685.v53b_070455063
    - github-branch-source:1983.vfa_27ed961853
    - matrix-auth:3.3

  overwritePlugins: true

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

    limits:
      cpu: "2"
      memory: 2Gi

  serviceAccount:
    create: true
    name: jenkins-controller-sa


agent:
  serviceAccount:
    name: jenkins-agent-sa

    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::524558748637:role/jenkins-agent-role


persistence:
  enabled: true
  size: 20Gi
  storageClass: efs-sc