name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform

    steps:

      - name: Checkout terraform/testing
        uses: actions/checkout@v4
        with:
          ref: terraform/testing

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init


      - name: Check Terraform State
        run: terraform state list

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="envs/dev.tfvars"

